### ISSUE TITLE
resolv.conf setting

### ISSUE THREAD

**Issue by fizzball** [obi12341/docker-unbound#1]
hi, was using and found i needed to set resolv.conf to 127.0.0.1 in order for requests to be serviced by unbound... thus modified run line became - 

docker run --name unbound -d -p 53:53/udp -p 53:53 --dns="127.0.0.1" secns/unbound:1.5.6

**Comment by obi12341** [comment]
The Container is just a Service as usual. so you have to set up clients to use unbound for name resolving

**Comment by fizzball** [comment]
understand Pat, however Service will pick up default resolver settings of the docker machine that is hosting it via Dhclient, thus any clients configured to use Service as their DNS will not be effected by the Unbound configuration that is listening on Interface 0.0.0.0. You need to set container's DNS resolver to also use localhost in order for it to process Client requests correctly. e.g.

currently: Client --> TCP/UDP 53 --> Docker Machine --> Container --> dhclient resolver (Unbound not processed)

suggest: Client --> TCP/UDP 53 --> Docker Machine --> Container --> localhost --> Unbound

Best, Fizz

**Comment by obi12341** [comment]
Still don't get it 100%. You are just talking about docker-machine, right? Because, for example, on a linux OS you can just deploy the container on :53 tcp/udp and can use 127.0.0.1 in resolv.conf.

BTW: Thanks for your interest :+1:

**Comment by fizzball** [comment]
That's correct Pat - however if deployed within Amazon ECS, resolv.conf of the container is managed by Amazon EC2, thus you cannot just set to 127.0.0.1 as it gets overwritten by the VPC default DHCP settings. Thus using the docker --dns option resolves this constraint. 

Great image by the way - working a treat!

**Comment by obi12341** [comment]
thanks for your explanation. I will add a section to the readme later :+1:

**Comment by fizzball** [comment]
All good Pat.

Btw, would be nice to be able to access logs in future... i updated unbound.conf to use the file /usr/local/etc/unbound/unbound.log for logging; then added a RUN command into Dockerfile to create the initial file e.g. -

RUN touch /usr/local/etc/unbound/unbound.log

However using the docker run -v /logs:/usr/local/etc/unbound switch resulted in only the unbound.pid file being displayed in the Docker Host machine /logs directory. Not sure why the other files in the unbound container directory were not shown? Maybe it has to do with the permissions?

Rgds,

Ramon

**Comment by obi12341** [comment]
Hey,
no need to specify a log file. You can just use: `-e VERBOSITY=5` and use `docker logs -f unbound`

**Comment by fizzball** [comment]
Cheers, will give it a try.

R
