### ISSUE TITLE
Setting Authoritative NS'

### ISSUE THREAD

**Issue by quantum77** [obi12341/docker-unbound#20]
I can't find your email address nor any way to contact you, so here we are.

I've adapted this into a podman pod, and I see how the internal unbound.conf is set.  But there doesn't seem to be any way to set forward requests to for recursion. ('forward-zone')

Sure I could modify unbound.conf or add a file, but I have the container set for auto update and this would be overwritten.  What to do?

**Comment by quantum77** [comment]
Helloo, is anybody out there?

**Comment by quantum77** [comment]
Uh oh, no response.

**Comment by obi12341** [comment]
man i am not your personal support...
Just mount a custom unbound.conf into the container or do a merge request and add the feature to the image.

**Comment by quantum77** [comment]
Yeah I ditched it.

Unusable.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
