### ISSUE TITLE
support with adguard

### ISSUE THREAD

**Issue by Rar9** [obi12341/docker-unbound#22]
Can u help me how to get unbound + adguard setup?

So for adguard dns I would just add 127.0.0.1:5335 for ip4 and [..1]:5335 for ip6

Here my .yml

`version: "3"
services:
  unbound:
    image: ajoergensen/unbound
    container_name: unbound

    ports:
      - 53:53/udp
      - 53:53

    environment:
      - DO_IPV6=yes
      - DO_IPV4=yes
      - DO_UDP=yes
      - DO_TCP=yes
      - VERBOSITY=0
      - NUM_THREADS=1
      - SO_RCVBUFF=0
      - SO_SNDBUF=0
      - SO_REUSEPORT=no
      - EDNS_BUFFER_SIZE=4096
      - MSG_CACHE_SIZE=4m
      - RRSET_CACHE_SIZE=4m
      - CACHE_MIN_TTL=0
      - CACHE_MAX_TTL=86400
      - CACHE_MAX_NEGATIVE_TTL=3600
      - HIDE_IDENTITY=yes
      - HIDE_VERSION=yes
      - STATISTICS_INTERVAL=0
      - STATISTICS_CUMULATIVE=no
      - EXTENDED_STATISTICS=no

    restart: always

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome

    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf

    ports:
      - 5335:53/tcp
      - 5335:53/udp
      - 380:80/tcp
      - 3000:3000/tcp
      - 367:67/udp
      - 368:68/tcp
      - 368:68/udp
      - 3443:443/tcp
      - 853:853/tcp
`

**Comment by obi12341** [comment]
sorry can't help you
