### ISSUE TITLE
Kindly update the image to version 1.14.0

### ISSUE THREAD

**Issue by Freekers** [obi12341/docker-unbound#23]
Please update the image to use version 1.14.0 :)

PS. Since Docker Hub has removed automatic image building for free accounts, let me know if you need help with setting up building images (for free) on Github and pushing them to Dockerhub.

**Comment by Meishop** [comment]
I join the request and would be very happy if the update could be transferred to dockerhub soon.

**Comment by obi12341** [comment]
Huhu,
because of docker changing features for free tier, I have to migrate this image to a new group that is paid because of automated builds feature. You can find updated images here: https://hub.docker.com/r/mobilistics/unbound

**Comment by Meishop** [comment]
Thanks a lot for the prompt reply and help!

**Comment by Freekers** [comment]
Thanks for the update and push to Dockerhub. Closing :)
